# Generated by Django 6.0.3 on 2026-08-15 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AeoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('topic', models.CharField(max_length=160)),
                ('market', models.CharField(default='Ireland', max_length=80)),
                ('language', models.CharField(default='en-IE', max_length=20)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('schema_type', models.CharField(default='FAQPage', max_length=80)),
                ('authority_score', models.PositiveSmallIntegerField(default=0)),
                ('citations', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttentionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=220)),
                ('impact', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(max_length=120)),
                ('recommendation', models.TextField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('trigger', models.CharField(max_length=220)),
                ('conditions', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('status', models.CharField(default='active', max_length=30)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('successes', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('channel', models.CharField(default='Email', max_length=80)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('audience_size', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('action', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('type', models.CharField(max_length=30)),
                ('channel', models.CharField(max_length=80)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('body', models.TextField()),
                ('seo_score', models.PositiveSmallIntegerField(default=0)),
                ('ai_confidence', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('subject', models.CharField(max_length=220)),
                ('preview_text', models.CharField(blank=True, max_length=260)),
                ('content', models.TextField()),
                ('segment', models.CharField(max_length=120)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('market', models.CharField(max_length=80)),
                ('system', models.CharField(max_length=120)),
                ('campaign', models.CharField(max_length=180)),
                ('channel', models.CharField(max_length=80)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('customers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('market', models.CharField(default='Ireland', max_length=80)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='new', max_length=30)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('subject', models.CharField(max_length=220)),
                ('category', models.CharField(max_length=80)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=50)),
                ('language', models.CharField(default='en_IE', max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(default='draft', max_length=30)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('replies', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AiDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_id', models.CharField(max_length=50, unique=True)),
                ('engine', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=220)),
                ('recommendation', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('impact', models.CharField(max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('governance_level', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('expected_outcome', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=160)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('type', models.CharField(default='text', max_length=30)),
                ('is_secret', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'key'), name='unique_setting')],
            },
        ),
    ]
