# Generated by Django 6.0.3 on 2026-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagedelivery_emailcampaign_failures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeoentry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='run_every_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Scheduler runs this workflow when it has not run for this many minutes.'),
        ),
    ]
