# Generated by Django 6.0.3 on 2026-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aeoentry_published_at_automation_run_every_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionitem',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('', 'Schedule only'), ('lead.created', 'Lead created'), ('lead.consented', 'Lead gave consent'), ('campaign.sent', 'Email campaign finished sending'), ('delivery.failed', 'Message delivery failed'), ('attention.overdue', 'Attention item passed its deadline')], default='', help_text='Fire immediately when this happens, instead of waiting for the schedule.', max_length=40),
        ),
    ]
