# Generated by Django 6.0.3 on 2026-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attentionitem_overdue_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('', 'Schedule only'), ('lead.created', 'Lead created'), ('lead.consented', 'Lead gave consent'), ('campaign.sent', 'Email campaign finished sending'), ('delivery.failed', 'Message delivery failed'), ('attention.overdue', 'Attention item passed its deadline'), ('lead.dormant', 'Lead has gone quiet'), ('lead.bounced', 'Lead was unsubscribed after repeated bounces')], default='', help_text='Fire immediately when this happens, instead of waiting for the schedule.', max_length=40),
        ),
    ]
