# Generated by Django 6.0.3 on 2026-08-17 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_automation_trigger_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, help_text="`amount` converted into the organisation's base currency.", max_digits=14, null=True)),
                ('market', models.CharField(default='Ireland', max_length=80)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('attribution', models.CharField(choices=[('unattributed', 'Unattributed'), ('last-touch', 'Last touch'), ('manual', 'Manual')], default='unattributed', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rolled_up_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('open', 'Open'), ('click', 'Click'), ('unsubscribe', 'Unsubscribe')], max_length=20)),
                ('url', models.CharField(blank=True, max_length=600)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(default='EUR', max_length=3)),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('as_of', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('country', models.CharField(default='IE', max_length=2)),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('locale', models.CharField(default='en-IE', max_length=12)),
                ('timezone', models.CharField(default='Europe/Dublin', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='setting',
            name='unique_setting',
        ),
        migrations.AddField(
            model_name='attentionitem',
            name='alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attentionitem',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attentionitem',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attentionitem',
            name='sla_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='unsubscribes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='campaign_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financials', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financials', to='core.emailcampaign'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('', 'Schedule only'), ('lead.created', 'Lead created'), ('lead.consented', 'Lead gave consent'), ('lead.engaged', 'Lead opened or clicked a campaign'), ('campaign.sent', 'Email campaign finished sending'), ('campaign.underperforming', 'Campaign engagement below target'), ('conversion.recorded', 'Lead converted with revenue'), ('delivery.failed', 'Message delivery failed'), ('attention.overdue', 'Attention item passed its deadline'), ('attention.escalated', 'Attention item breached its deadline again'), ('lead.dormant', 'Lead has gone quiet'), ('lead.bounced', 'Lead was unsubscribed after repeated bounces')], default='', help_text='Fire immediately when this happens, instead of waiting for the schedule.', max_length=40),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event'], name='core_auditl_event_5754ec_idx'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['email'], name='core_consen_email_10eafa_idx'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['created_at'], name='core_consen_created_1323a3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['channel', 'status'], name='core_messag_channel_dc97b2_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['recipient'], name='core_messag_recipie_fcf8de_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['created_at'], name='core_messag_created_3478c2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['started_at'], name='core_workfl_started_ec54dc_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['status'], name='core_workfl_status_c1c3dc_idx'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='core.emailcampaign'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='core.lead'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='core.messagedelivery'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('base', 'currency', 'as_of'), name='unique_fx_rate'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='aeoentry',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='aidecision',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='attentionitem',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='automation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='integration',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='setting',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organisation'),
        ),
        migrations.AddIndex(
            model_name='attentionitem',
            index=models.Index(fields=['status', 'severity'], name='core_attent_status_b0e205_idx'),
        ),
        migrations.AddIndex(
            model_name='attentionitem',
            index=models.Index(fields=['due_at'], name='core_attent_due_at_980dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='attentionitem',
            index=models.Index(fields=['category'], name='core_attent_categor_63e9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='core_emailc_status_40e2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['sent_at'], name='core_emailc_sent_at_3cd9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['recorded_on'], name='core_financ_recorde_507198_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['channel'], name='core_financ_channel_7a79cb_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['market'], name='core_financ_market_4a7310_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='core_lead_status_7318b1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['consent_at'], name='core_lead_consent_d3039e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['updated_at'], name='core_lead_updated_2c7fbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('organisation', 'group', 'key'), name='unique_setting_per_org'),
        ),
        migrations.AddIndex(
            model_name='engagementevent',
            index=models.Index(fields=['kind', 'created_at'], name='core_engage_kind_2c8555_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['occurred_at'], name='core_conver_occurre_c2ed20_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['rolled_up_at'], name='core_conver_rolled__c7ae9a_idx'),
        ),
    ]
